#!/bin/bash

assignment_overlaps() {
    if [ $2 -ge $3 ] && [ $4 -ge $1 ]; then
        echo "1"
    else
        echo "0"
    fi        
}

count=0
while read -r assignment_pair; do
    pair=($(echo $assignment_pair | awk -F',' '{ print $1;print $2 }' | awk -F'-' '{ print $1;print $2 }'))
    s11=${pair[0]}
    s12=${pair[1]}
    s21=${pair[2]}
    s22=${pair[3]}

    is_overlaped=$(assignment_overlaps $s11 $s12 $s21 $s22)

    if [ $is_overlaped -eq 0 ]; then
        is_overlaped=$(assignment_overlaps $s21 $s22 $s11 $s12)
    fi

    let "count = count + is_overlaped"
done < <(grep "" $1)

echo $count

