#!/bin/bash

group_number=0
count=0
while read -r rucksack; do
    if [ $(($count%3)) -eq 0 ]; then
        let "group_number = group_number + 1"
    fi
    echo $rucksack >> group$group_number
    let "count = count + 1"
done < <(grep "" $1)