#!/bin/bash
rm -rf calories*.txt
count=1
while read -r line; do
   if [[ $line != "" ]]; then
	   echo $line >> calories$count.txt
   else
        awk '{s+=$1} END {print s}' calories$count.txt
   	let "count = count + 1"
   fi
done < calories
rm -rf calories*.txt
